### ISSUE TITLE
AttributeError: 'GbmRsp2' object has no attribute 'drm'

### ISSUE THREAD

**Issue by nyctophile-aayu** [USRA-STI/gdt-fermi#34]
I am running spectral analysis for GBM data:

specfitter = SpectralFitterPgstat(phas, bkgds.to_list(), rsps.to_list(), method='TNC')

band = Band()

print('Band Fit:')
# specfitter.fit(band)
specfitter.fit(band, options={'maxiter': 1000})

Error:
Band Fit:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[42], line 3
      1 print('Band Fit:')
      2 # specfitter.fit(band)
----> 3 specfitter.fit(band, options={'maxiter': 1000})
      5 # After the fit has converged, we can query the fitter for lots of info, including the parameters that
      6 # satisfy the maximum likelihood as well as the parameter uncertainties resulting from -2(Delta)LogLike
      7 print(specfitter.success)

File [~/gdt-core/src/gdt/core/spectra/fitting.py:454](http://localhost:8890/home/lonewolf/gdt-core/src/gdt/core/spectra/fitting.py#line=453), in SpectralFitter.fit(self, function, **kwargs)
    452 with warnings.catch_warnings():
    453     warnings.simplefilter("ignore")
--> 454     res = minimize(self._eval_stat_jac, init_params, args=(function,),
    455                    method=self._method, bounds=function.parameter_bounds(),
    456                    jac=True, hess=hess, **kwargs)
    457 self._res = res

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_minimize.py:716](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_minimize.py#line=715), in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    713     res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
    714                            callback=callback, **options)
    715 elif meth == 'tnc':
--> 716     res = _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
    717                         **options)
    718 elif meth == 'cobyla':
    719     res = _minimize_cobyla(fun, x0, args, constraints, callback=callback,
    720                            bounds=bounds, **options)

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_tnc.py:381](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_tnc.py#line=380), in _minimize_tnc(fun, x0, args, jac, bounds, eps, scale, offset, mesg_num, maxCGit, eta, stepmx, accuracy, minfev, ftol, xtol, gtol, rescale, disp, callback, finite_diff_rel_step, maxfun, **unknown_options)
    378 else:
    379     messages = MSG_NONE
--> 381 sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
    382                               finite_diff_rel_step=finite_diff_rel_step,
    383                               bounds=new_bounds)
    384 func_and_grad = sf.fun_and_grad
    386 """
    387 low, up   : the bounds (lists of floats)
    388             if low is None, the lower bounds are removed.
    389             if up is None, the upper bounds are removed.
    390             low and up defaults to None
    391 """

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_optimize.py:402](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_optimize.py#line=401), in _prepare_scalar_function(fun, x0, jac, args, bounds, epsilon, finite_diff_rel_step, hess)
    398     bounds = (-np.inf, np.inf)
    400 # ScalarFunction caches. Reuse of fun(x) during grad
    401 # calculation reduces overall function evaluations.
--> 402 sf = ScalarFunction(fun, x0, args, grad, hess,
    403                     finite_diff_rel_step, bounds, epsilon=epsilon)
    405 return sf

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py:166](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py#line=165), in ScalarFunction.__init__(self, fun, x0, args, grad, hess, finite_diff_rel_step, finite_diff_bounds, epsilon)
    163     self.f = fun_wrapped(self.x)
    165 self._update_fun_impl = update_fun
--> 166 self._update_fun()
    168 # Gradient evaluation
    169 if callable(grad):

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py:262](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py#line=261), in ScalarFunction._update_fun(self)
    260 def _update_fun(self):
    261     if not self.f_updated:
--> 262         self._update_fun_impl()
    263         self.f_updated = True

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py:163](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py#line=162), in ScalarFunction.__init__.<locals>.update_fun()
    162 def update_fun():
--> 163     self.f = fun_wrapped(self.x)

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py:145](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py#line=144), in ScalarFunction.__init__.<locals>.fun_wrapped(x)
    141 self.nfev += 1
    142 # Send a copy because the user may overwrite it.
    143 # Overwriting results in undefined behaviour because
    144 # fun(self.x) will change self.x, with the two no longer linked.
--> 145 fx = fun(np.copy(x), *args)
    146 # Make sure the function returns a true scalar
    147 if not np.isscalar(fx):

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_optimize.py:78](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_optimize.py#line=77), in MemoizeJac.__call__(self, x, *args)
     76 def __call__(self, x, *args):
     77     """ returns the function value """
---> 78     self._compute_if_needed(x, *args)
     79     return self._value

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_optimize.py:72](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_optimize.py#line=71), in MemoizeJac._compute_if_needed(self, x, *args)
     70 if not np.all(x == self.x) or self._value is None or self.jac is None:
     71     self.x = np.asarray(x).copy()
---> 72     fg = self.fun(x, *args)
     73     self.jac = fg[1]
     74     self._value = fg[0]

File [~/gdt-core/src/gdt/core/spectra/fitting.py:748](http://localhost:8890/home/lonewolf/gdt-core/src/gdt/core/spectra/fitting.py#line=747), in SpectralFitter._eval_stat_jac(self, params, function)
    737 def _eval_stat_jac(self, params, function):
    738     """Evaluate the statistic (and Jacobian of the statistic as a function
    739     of the model parameters).
    740     
   (...)
    746         (float, np.array)
    747     """
--> 748     stat = self._fold_model(function.fit_eval, params)
    749     jac = self._jacobian(params, function)
    750     return -stat, -jac

File [~/gdt-core/src/gdt/core/spectra/fitting.py:770](http://localhost:8890/home/lonewolf/gdt-core/src/gdt/core/spectra/fitting.py#line=769), in SpectralFitter._fold_model(self, function, params)
    767 stat = np.zeros(self.num_sets)
    768 for i in range(self.num_sets):
    769     # fold model through response and convert to raw model counts
--> 770     model = self._rsp[i].drm.fold_spectrum(function, params, channel_mask=self._chan_masks[i])
    772     # perform likelihood calculation for one dataset
    773     stat[i] = self._eval_stat(i, model)

AttributeError: 'GbmRsp2' object has no attribute 'drm'

My query is how to fix both of these errors? Is there any other way around for it in GDT? 
Can I skip the channel mask step and apply any other step to put constraint on the k-edge energy window (32-35 keV)? If yes, then how?

**Comment by AdamGoldstein-USRA** [comment]
@nyctophile-aayu The GbmRsp2 class interfaces with Type 2 response files, which are a time series of detector response matrices.  This is different from the more typical Type 1 response file that has a single matrix.  When you pass a GbmRsp2 object to the spectral fitter, it does not know which response matrix you intend to use.  Therefore, you must extract a single response from GbmRsp2.  This can be done several ways: extract_drm() or nearest_drm() will extract a single response from GbmRsp2 (and return a GbmRsp object) based on a time or index selection; interpolate() will create a single response by interpolating the series of responses in GbmRsp2 at the input time; or weighted() which will create a new response that is weighted by the number of detected counts over a time range.  Once you have extracted a response from the GbmRsp2 object, you can pass that to the spectral fitter.  See [here ](https://astro-gdt.readthedocs.io/projects/astro-gdt-fermi/en/latest/api/gdt.missions.fermi.gbm.response.GbmRsp2.html#gdt.missions.fermi.gbm.response.GbmRsp2)for more details on the GbmRsp2 class.

**Comment by nyctophile-aayu** [comment]
@AdamGoldstein-USRA I have tried to fix that and even tried to run a single detector and response file, then tried to run the spectral fitting. Just like how it was described in the `Spectral Fitting` notebook in the GBM data tools (ofcourse after correcting for GDT modules), but it is still not processing the fitting.

from gdt.missions.fermi.gbm.response import GbmRsp2
rsp = GbmRsp2.open('data1/glg_cspec_n0_bn220627890_v02.rsp2')
# the DRM that is nearest to our time of interest
nearest_drm = rsp.extract_drm(atime=pha.tcent)
# the interpolated DRM
interp_drm = rsp.interpolate(pha.tcent)


The results of both of these code lines are same:
specfitter.fit(Band())
OR
band = Band()
specfitter.fit(band, options={'maxiter': 1000})


Error:
AttributeError                            Traceback (most recent call last)
Cell In[33], line 3
      1 print('Band Fit:')
      2 # specfitter.fit(rsps_interp, band)
----> 3 specfitter.fit(band, options={'maxiter': 1000})
      5 # After the fit has converged, we can query the fitter for lots of info, including the parameters that
      6 # satisfy the maximum likelihood as well as the parameter uncertainties resulting from -2(Delta)LogLike
      7 print(specfitter.success)

File [~/gdt-core/src/gdt/core/spectra/fitting.py:454](http://localhost:8890/home/lonewolf/gdt-core/src/gdt/core/spectra/fitting.py#line=453), in SpectralFitter.fit(self, function, **kwargs)
    452 with warnings.catch_warnings():
    453     warnings.simplefilter("ignore")
--> 454     res = minimize(self._eval_stat_jac, init_params, args=(function,),
    455                    method=self._method, bounds=function.parameter_bounds(),
    456                    jac=True, hess=hess, **kwargs)
    457 self._res = res

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_minimize.py:716](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_minimize.py#line=715), in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    713     res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
    714                            callback=callback, **options)
    715 elif meth == 'tnc':
--> 716     res = _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,
    717                         **options)
    718 elif meth == 'cobyla':
    719     res = _minimize_cobyla(fun, x0, args, constraints, callback=callback,
    720                            bounds=bounds, **options)

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_tnc.py:381](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_tnc.py#line=380), in _minimize_tnc(fun, x0, args, jac, bounds, eps, scale, offset, mesg_num, maxCGit, eta, stepmx, accuracy, minfev, ftol, xtol, gtol, rescale, disp, callback, finite_diff_rel_step, maxfun, **unknown_options)
    378 else:
    379     messages = MSG_NONE
--> 381 sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
    382                               finite_diff_rel_step=finite_diff_rel_step,
    383                               bounds=new_bounds)
    384 func_and_grad = sf.fun_and_grad
    386 """
    387 low, up   : the bounds (lists of floats)
    388             if low is None, the lower bounds are removed.
    389             if up is None, the upper bounds are removed.
    390             low and up defaults to None
    391 """

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_optimize.py:402](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_optimize.py#line=401), in _prepare_scalar_function(fun, x0, jac, args, bounds, epsilon, finite_diff_rel_step, hess)
    398     bounds = (-np.inf, np.inf)
    400 # ScalarFunction caches. Reuse of fun(x) during grad
    401 # calculation reduces overall function evaluations.
--> 402 sf = ScalarFunction(fun, x0, args, grad, hess,
    403                     finite_diff_rel_step, bounds, epsilon=epsilon)
    405 return sf

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py:166](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py#line=165), in ScalarFunction.__init__(self, fun, x0, args, grad, hess, finite_diff_rel_step, finite_diff_bounds, epsilon)
    163     self.f = fun_wrapped(self.x)
    165 self._update_fun_impl = update_fun
--> 166 self._update_fun()
    168 # Gradient evaluation
    169 if callable(grad):

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py:262](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py#line=261), in ScalarFunction._update_fun(self)
    260 def _update_fun(self):
    261     if not self.f_updated:
--> 262         self._update_fun_impl()
    263         self.f_updated = True

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py:163](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py#line=162), in ScalarFunction.__init__.<locals>.update_fun()
    162 def update_fun():
--> 163     self.f = fun_wrapped(self.x)

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py:145](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_differentiable_functions.py#line=144), in ScalarFunction.__init__.<locals>.fun_wrapped(x)
    141 self.nfev += 1
    142 # Send a copy because the user may overwrite it.
    143 # Overwriting results in undefined behaviour because
    144 # fun(self.x) will change self.x, with the two no longer linked.
--> 145 fx = fun(np.copy(x), *args)
    146 # Make sure the function returns a true scalar
    147 if not np.isscalar(fx):

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_optimize.py:78](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_optimize.py#line=77), in MemoizeJac.__call__(self, x, *args)
     76 def __call__(self, x, *args):
     77     """ returns the function value """
---> 78     self._compute_if_needed(x, *args)
     79     return self._value

File [~/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_optimize.py:72](http://localhost:8890/home/lonewolf/miniforge3/envs/gdt/lib/python3.12/site-packages/scipy/optimize/_optimize.py#line=71), in MemoizeJac._compute_if_needed(self, x, *args)
     70 if not np.all(x == self.x) or self._value is None or self.jac is None:
     71     self.x = np.asarray(x).copy()
---> 72     fg = self.fun(x, *args)
     73     self.jac = fg[1]
     74     self._value = fg[0]

File [~/gdt-core/src/gdt/core/spectra/fitting.py:748](http://localhost:8890/home/lonewolf/gdt-core/src/gdt/core/spectra/fitting.py#line=747), in SpectralFitter._eval_stat_jac(self, params, function)
    737 def _eval_stat_jac(self, params, function):
    738     """Evaluate the statistic (and Jacobian of the statistic as a function
    739     of the model parameters).
    740     
   (...)
    746         (float, np.array)
    747     """
--> 748     stat = self._fold_model(function.fit_eval, params)
    749     jac = self._jacobian(params, function)
    750     return -stat, -jac

File [~/gdt-core/src/gdt/core/spectra/fitting.py:770](http://localhost:8890/home/lonewolf/gdt-core/src/gdt/core/spectra/fitting.py#line=769), in SpectralFitter._fold_model(self, function, params)
    767 stat = np.zeros(self.num_sets)
    768 for i in range(self.num_sets):
    769     # fold model through response and convert to raw model counts
--> 770     model = self._rsp[i].drm.fold_spectrum(function, params, channel_mask=self._chan_masks[i])
    772     # perform likelihood calculation for one dataset
    773     stat[i] = self._eval_stat(i, model)

AttributeError: 'GbmRsp2' object has no attribute 'drm'


Please suggest how to fix this. 

Considering the amount of time I am wasting on GDT, now I feel GBM data tools were better. :'( :'( :'(

**Comment by AdamGoldstein-USRA** [comment]
> AttributeError: 'GbmRsp2' object has no attribute 'drm'

This is at the bottom of your error trace.  This means you are passing a GbmRsp2 object to the fitter instead of the extracted or interpolated response.

**Comment by nyctophile-aayu** [comment]
@AdamGoldstein-USRA I got it thanks. It is working now. I was not inserting the interpolated rsps in Specfitter definition.
