### ISSUE TITLE
Possible bug with GbmDetectorCollection 

### ISSUE THREAD

**Issue by OliverRoberts-USRA** [USRA-STI/gdt-fermi#4]
I tried to convert TTE detector data to a PHAII format so that I can group detectors for spectral fitting using GbmDetectorCollection. I follow the examples in the GBM Data Tools and GDT documentation [https://fermi.gsfc.nasa.gov/ssc/data/analysis/rmfit/gbm_data_tools/gdt-docs/notebooks/SpectralFitting.html](url) but get errors  when trying to fit a background to a list of detectors. However, working through the error seems to show an empty list after using GbmDetectorCollection. The conversion beforehand from TTE to PHAII seems to work fine, but the collection element does not seem to populate a list after. I could be doing something wrong, but I am struggling to see the issue and would appreciate some feedback.  I am using a MacOS (Monterrey 12.6.5). Attached is a screenshot of the executed code.

<img width="911" alt="Screen Shot 2023-05-08 at 12 38 11 PM" src="https://user-images.githubusercontent.com/131705407/236892524-4fab3594-1a79-4413-8126-e164ac8260d7.png">

<img width="1093" alt="Screen Shot 2023-05-08 at 12 41 02 PM" src="https://user-images.githubusercontent.com/131705407/236893099-38f378eb-a59e-46cb-b408-ff64c1e7773a.png">

**Comment by AdamGoldstein-USRA** [comment]
I believe the bug is related to this [TODO](https://github.com/USRA-STI/gdt-fermi/blob/04f60fb605cf0d0402b1cc9cc15e8972196de07a/src/gdt/missions/fermi/gbm/tte.py#L54).  Essentially, the detector name is not copied over from the TTE when converting to a PHAII.  This can be confirmed by creating a collection with native CTIME or CSPEC data.

**Comment by OliverRoberts-USRA** [comment]
@AdamGoldstein-USRA Thanks for implementing a fix. I tested the [fix-tte-to-phaii-detector-name](https://github.com/USRA-STI/gdt-fermi/tree/fix-tte-to-phaii-detector-name) branch and found it worked successfully. Consider the bug resolved. Thank you!
