### ISSUE TITLE
Error when running pip install -r gdt-fermi/requirements.txt

### ISSUE THREAD

**Issue by lorenzoscotton** [USRA-STI/gdt-fermi#43]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
astro-gdt-fermi 2.1.3 requires matplotlib>=3.9.1, but you have matplotlib 3.8.4 which is incompatible.

**Comment by BillCleveland-USRA** [comment]
What version of python are you using?

**Comment by lorenzoscotton** [comment]
Python 3.10.12

**Comment by joshuarwood** [comment]
It looks like this might only be an issue when installing from the requirements.txt file?

pip installs matplotlib 3.9.1.post1 for me even if I roll the setup.py for gdt-fermi back to matplotlib 3.8.4. Also, we should update the requirements file to match the setup.py. I forgot to do that when updating the setup.py.

**Comment by lorenzoscotton** [comment]
Yup, I was installing from the requirements file. Setting matplotlib>=3.9.1 to match the setup.py solved the issue.

Thanks!
