### ISSUE TITLE
Add MET conversion for Time.py

### ISSUE THREAD

**Issue by CoriFletcher-USRA** [USRA-STI/gdt-fermi#7]
It would be nice to have an MET conversion in the Fermi time.py file.

**Comment by AdamGoldstein-USRA** [comment]
Can you elaborate?  We use astropy.Time to perform time conversions, and the Fermi MET is defined as a special epoch within time.py.  For example, you can do the following to get the Fermi MET for the current time:
`from gdt.missions.fermi.time import Time`
`Time.now().fermi`

Similarly, a Time object can be created with any other time, and as long as you've done the above import, the conversion to fermi using `.fermi` is available to you.

**Comment by AdamGoldstein-USRA** [comment]
@CoriFletcher-USRA can this be closed?
